package cli

import (
	"fmt"
	"os"
	"path/filepath"
)

// createRitualWithTemplates creates a ritual with optional example files
func createRitualWithTemplates(ritualName string, withExamples bool) error {
	// Use existing createRitual for basic structure
	if err := createRitual(ritualName); err != nil {
		return err
	}

	if !withExamples {
		return nil
	}

	// Add example files
	if err := addExampleTemplate(ritualName); err != nil {
		return err
	}

	if err := addGitignore(ritualName); err != nil {
		return err
	}

	if err := addMigrationGuide(ritualName); err != nil {
		return err
	}

	if err := enhanceRitualYAML(ritualName); err != nil {
		return err
	}

	if err := enhanceREADME(ritualName); err != nil {
		return err
	}

	fmt.Printf("\n✨ Created ritual template with examples!\n\n")
	fmt.Printf("Next steps:\n")
	fmt.Printf("  1. Edit %s/ritual.yaml to customize\n", ritualName)
	fmt.Printf("  2. Add more templates to %s/templates/\n", ritualName)
	fmt.Printf("  3. Test: ritual validate --path %s\n", ritualName)
	fmt.Printf("  4. Try: ritual init %s --output /tmp/test\n\n", ritualName)

	return nil
}

func addExampleTemplate(ritualName string) error {
	template := fmt.Sprintf(`package main

// %s - Generated by ritual

import (
	"fmt"
	"log"
)

func main() {
	fmt.Println("Welcome to {{ .project_name }}!")
	log.Println("Application started")
}
`, ritualName)

	path := filepath.Join(ritualName, "templates", "main.go.tmpl")
	return os.WriteFile(path, []byte(template), 0600)
}

func addGitignore(ritualName string) error {
	gitignore := `.ritual/
*.log
*.exe
*.test
*.out
vendor/
.vscode/
.idea/
.DS_Store
`
	path := filepath.Join(ritualName, "static", ".gitignore")
	return os.WriteFile(path, []byte(gitignore), 0600)
}

func addMigrationGuide(ritualName string) error {
	guide := `# Migration Example

Migrations allow you to update projects when your ritual version changes.

## Example

migrations:
  - from_version: "1.0.0"
    to_version: "1.1.0"
    description: "Add authentication"
    up:
      sql:
        - "CREATE TABLE users (id SERIAL PRIMARY KEY)"
    down:
      sql:
        - "DROP TABLE users"
`
	path := filepath.Join(ritualName, "migrations", "example.md")
	return os.WriteFile(path, []byte(guide), 0600)
}

func enhanceRitualYAML(ritualName string) error {
	yaml := fmt.Sprintf(`# Ritual manifest
ritual:
  name: %s
  version: 1.0.0
  description: A custom ritual
  author: ""

compatibility:
  min_touta_version: "0.1.0"
  min_go_version: "1.22"

# questions - asked during initialization
questions:
  - name: project_name
    type: text
    prompt: "Project name?"
    required: true
`, ritualName)

	yaml += `
# files - to generate
files:
  templates:
    - src: templates/main.go.tmpl
      dest: main.go
  static:
    - src: static/.gitignore
      dest: .gitignore
  protected: []

# hooks - commands to run
hooks:
  pre_install: []
  post_install:
    - "go mod tidy"
`

	path := filepath.Join(ritualName, "ritual.yaml")
	return os.WriteFile(path, []byte(yaml), 0600)
}

func enhanceREADME(ritualName string) error {
	readme := fmt.Sprintf(`# %s Ritual

Custom ritual template.

## Usage

ritual init %s

## Hooks

### pre_install Hooks

Run before file generation. Example:
- Validate environment
- Check dependencies

### post_install Hooks

Run after file generation. Example:
- go mod tidy
- Initialize database

## Customization

Edit ritual.yaml to add questions, templates, and hooks.

See docs at: https://github.com/toutaio/toutago-ritual-grove
`, ritualName, ritualName)

	path := filepath.Join(ritualName, "README.md")
	return os.WriteFile(path, []byte(readme), 0600)
}
